version: '3'

services:

  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_DATABASE: 'rest_db'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    networks:
      - rest
    volumes:
      - rest_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    restart: always

  php:
    image: php:8.1-fpm
    container_name: php
    working_dir: /app
    networks:
      - rest
    volumes:
      - ./app:/app
    depends_on:
      database:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    working_dir: /app
    networks:
      - rest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/app
    ports:
      - 80:80
    depends_on:
      database:
        condition: service_healthy
      php:
        condition: service_started
    restart: always




















networks:
  rest:
    name: 'rest'

volumes:
  rest_db:
    name: 'rest_db'